/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2018-06-04 13:44:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.site;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Collection;
import java.util.HashSet;
import org.apache.commons.lang3.ArrayUtils;
import jfix.servlet.Cookies;
import jease.Registry;
import jease.Names;
import jease.cms.domain.Access;
import jease.cms.domain.Content;
import jease.cms.domain.User;
import jease.site.Authorizations;
import jease.site.Templates;

public final class Dispatcher_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.HashSet");
    _jspx_imports_classes.add("jease.cms.domain.Access");
    _jspx_imports_classes.add("jease.cms.domain.User");
    _jspx_imports_classes.add("jfix.servlet.Cookies");
    _jspx_imports_classes.add("jease.cms.domain.Content");
    _jspx_imports_classes.add("java.util.Collection");
    _jspx_imports_classes.add("jease.site.Authorizations");
    _jspx_imports_classes.add("org.apache.commons.lang3.ArrayUtils");
    _jspx_imports_classes.add("jease.Registry");
    _jspx_imports_classes.add("jease.Names");
    _jspx_imports_classes.add("jease.site.Templates");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	// The current node is stored in request-attribute by JeaseServletFilter.
	Content node = (Content) request.getAttribute("Node");
	
	// Save original node as stable context, because "Node" is exchanged
	// in some templates on the fly (e.g. Folder, Reference, Composite).
	if (request.getAttribute("Context") == null) {
		request.setAttribute("Context", node);
	}
		
	// If an Access-Object is guarding the node, use it to force authorization.
	String authorization = request.getHeader("Authorization");
	Access[] guards = Authorizations.getGuards(node);
	if (ArrayUtils.isNotEmpty(guards)) {
		Access guard = Authorizations.findAuthorizingGuard(authorization, guards);
		if (guard != null) {
			if (session.getAttribute(Names.JEASE_SITE_AUTHORIZATIONS) == null) {
				session.setAttribute(Names.JEASE_SITE_AUTHORIZATIONS, new HashSet<Object>());
			}
			((Collection<Object>) session.getAttribute(Names.JEASE_SITE_AUTHORIZATIONS)).add(guard);
		} else {
			// If current user can view content in the CMS, skip authorization.
			User user = (User) session.getAttribute(User.class.toString());
			for (Access access : guards) {
				if (user == null || !access.isDescendant(user.getRoots())) {
					request.setAttribute("Node", node = access);
					break;
				}
			}
		}
	}

	// Which template should be used to render the node?
	String pageTemplate = Templates.get(node);

	// If node is page-like content (e.g. text) and no file-parameter exists in request,
	// then include template, otherwise forward (e.g. to stream binary content).
	if (node.isPage() && request.getParameter("file") == null) {
		String template = request.getParameter("page");
		if (template != null && !template.startsWith("/WEB-INF") && !template.endsWith("Page.jsp") 
				&& !template.equals((String) request.getAttribute(Names.JEASE_SITE_DISPATCHER))) {
			pageTemplate = template;
		}
		request.setAttribute("Page.Template", pageTemplate);
		String design = Registry.getParameter(Names.JEASE_SITE_DESIGN);
		if (design != null) {
			if (design.startsWith("/")) {
				pageContext.forward(design);
			} else {
				// Check if user design is requested via cookie.
				String userDesign = Cookies.pick(request, response, "design", null);
				if (userDesign != null && !userDesign.contains("/")) {
					String userDesignPath = String.format("/site/web/%s/Page.jsp", userDesign);
					String userDesignRealPath = application.getRealPath(userDesignPath);
					if (userDesignRealPath != null && new java.io.File(userDesignRealPath).exists()) {
						pageContext.forward(userDesignPath);
						return;
					}
				}
				pageContext.forward(String.format("/site/web/%s/Page.jsp", design));
			}
		}
	} else {
		pageContext.forward(pageTemplate);
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
